import "./globals.css";
import { Lora, Karla } from "next/font/google";
import Header from "@/components/Header";

const lora = Lora({ subsets: ["latin"], variable: "--font-subtitle" });
const karla = Karla({ subsets: ["latin"], variable: "--font-body" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${lora.variable} ${karla.variable}`}>
      <body>
        <Header />
        <div className="">{children}</div>
      </body>
    </html>
  );
}
